# Generated by Django 6.0.1 on 2026-02-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
