# Generated by Django 6.0.1 on 2026-02-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0005_alter_comment_created_at_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
