# Generated by Django 6.0.1 on 2026-02-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0006_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
