# Generated by Django 6.0.1 on 2026-03-08 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0007_alter_post_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
